"""
Django settings for getLost project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
# import moneyed
# from moneyed.localization import _FORMATTER
# from decimal import ROUND_HALF_EVEN

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o_8$3h*5+3q1u1$b*lc($u@y+qqd71-p6y996e%1pclc$2z&dr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    # 'admin_reorder',
    'rest_framework.authtoken',
    'rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rest_auth.registration',

    'bootstrap_datepicker_plus',
    'djmoney',
    'currencies',
    'admin_interface',      # theme for admin
    'colorfield',           # theme for admin
    'django_countries',

    'bootstrap4',
    'users.apps.UsersConfig',
    'webApp.apps.WebappConfig', # added this so that webApp.views could connect to html
    'apis.apps.ApisConfig',
    'crispy_forms',
    'phonenumber_field',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'getLost.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'currencies.context_processors.currencies',
            ],
        },
    },
]

AUTH_USER_MODEL = 'users.User' #authenticating users using my custome user model

WSGI_APPLICATION = 'getLost.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'user_db',
#         'USER': 'postgres',
#         'PASSWORD': 'getlost1298',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'user_db2',
        'USER': 'dev',
        'PASSWORD': 'F:}Y(k#a49!N',
        'HOST': '35.235.115.47',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 9,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.IsAuthenticatedOrReadOnly'
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
# Replace when website is in production
# STATIC_ROOT = os.path.join(BASE_DIR, '/static/')

CRISPY_TEMPLATE_PACK = 'bootstrap4'

##redirecting to home page after login
LOGIN_REDIRECT_URL = 'home'
##redirect to login page when trying to enter profile without being logged in
LOGIN_URL = 'login'

# During development only
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")

# SMTP CONFIGURATION
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ADD EMAIL'
EMAIL_HOST_PASSWORD = 'ADD PASSWORD FOR EMAIL'
# ACCOUNT_EMAIL_VARIFICATION = 'none'

MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

X_FRAME_OPTIONS = 'SAMEORIGIN'

STRIPE_PUBLISHABLE_KEY = 'pk_test_51H0CQsHCy8Q2hv8oOWqUqzmCH9x80R555acMCP1QPVmbcLrF47nX2pwBgqUxsOsFjUUoyp0MYvLBCSUMbhBHqISx002ei3qvVk'
STRIPE_SECRET_KEY = 'sk_test_51H0CQsHCy8Q2hv8oGTfA16tkNPaKKLck0IPQTuVKK5In3ii5KK4x4110gH8eXa3UVBJdXXWWy5SCN8E1dDuo880p00MhYjL0r2'
STRIPE_CONNECT_CLIENT_ID = 'ca_HZL836YcEP558g4TZL07lyrEM9HO9FRa'

# Django Money
# BOB = moneyed.add_currency(
#     code='BOB',
#     numeric='068',
#     name='Peso boliviano',
#     countries=('BOLIVIA', )
# )

# # Currency Formatter will output 2.000,00 Bs.
# _FORMATTER.add_sign_definition(
#     'default',
#     BOB,
#     prefix=u'Bs. '
# )

# _FORMATTER.add_formatting_definition(
#     'es_BO',
#     group_size=3, group_separator=".", decimal_point=",",
#     positive_sign="",  trailing_positive_sign="",
#     negative_sign="-", trailing_negative_sign="",
#     rounding_method=ROUND_HALF_EVEN
# )

# CURRENCIES = ('USD', 'EUR', 'BOB')
# CURRENCY_CHOICES = [('USD', 'USD $'), ('EUR', 'EUR €')]

# ADMIN_REORDER = (
#     # Keep original label and models
#     'sites',

#     {'app': 'users', 'label': 'users',
#         'models': (
#             'users.Profile',
#             'users.RoomDetail',
#             'users.Request',
#             'users.User',
#             'users.Reservation',
#             'users.CustomerProfile',
#             'users.currency',
#             'admin_interface.theme',
#             'currencies.context_processors.currencies',

#         )
#      },
#     {'app': 'currencies.context_processors', 'label': 'currencies',
#         'models': (
            
#             'currencies.context_processors.currencies',
            

#         )
#      },
   
# )
