# Generated by Django 3.0.6 on 2020-06-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hostel',
            field=models.BooleanField(default=True),
        ),
    ]
