# Generated by Django 3.0.6 on 2020-06-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_reservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdetail',
            old_name='avaliablity',
            new_name='avaliability',
        ),
        migrations.RenameField(
            model_name='roomdetail',
            old_name='total_beds',
            new_name='occupied_beds',
        ),
    ]
