# Generated by Django 3.0.6 on 2020-06-12 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200612_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetail',
            name='hostel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
