# Generated by Django 3.0.6 on 2020-06-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_reservation_is_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='total_bed_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
