# Generated by Django 3.0.6 on 2020-06-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200630_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
