# Generated by Django 3.0.6 on 2020-06-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200630_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdetail',
            old_name='total_bed_password',
            new_name='price_password',
        ),
    ]
