# Generated by Django 3.0.6 on 2020-06-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200630_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='total_beds_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
