# Generated by Django 3.0.6 on 2020-07-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_roomdetail_total_beds_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetail',
            name='avaliability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='occupied_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='total_coed_beds',
            field=models.IntegerField(default=0),
        ),
    ]
