# Generated by Django 3.0.6 on 2020-07-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200702_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
