# Generated by Django 3.0.6 on 2020-07-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200703_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='country',
        ),
    ]
