# Generated by Django 3.0.6 on 2020-07-04 04:15

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_customerprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
