# Generated by Django 3.0.6 on 2020-07-07 03:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200704_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(blank=True, default='none', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='emergency_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='none', max_length=20, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+11234567890', max_length=20, null=True, region=None),
        ),
    ]
