# Generated by Django 3.0.6 on 2020-07-07 04:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20200707_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='emergency_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='e.g. +12125552368', max_length=20, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1, null=True),
        ),
    ]
