# Generated by Django 3.0.6 on 2020-07-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200707_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='made_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
