# Generated by Django 3.0.6 on 2020-07-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
