# Generated by Django 3.0.6 on 2020-07-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
