# Generated by Django 3.0.6 on 2020-07-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20200714_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
