# Generated by Django 3.0.6 on 2020-07-14 03:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20200714_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 3, 37, 33, 24248, tzinfo=utc), editable=False, null=True),
        ),
    ]
