# Generated by Django 3.0.6 on 2020-08-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20200714_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='employee_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
