# Generated by Django 3.0.6 on 2020-09-09 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20200909_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
