# Generated by Django 3.0.6 on 2020-09-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_delete_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hostel',
            field=models.BooleanField(default=True),
        ),
    ]
