# Generated by Django 3.0.6 on 2020-09-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_user_is_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_hostel',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
