# Generated by Django 3.0.6 on 2020-09-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('1', 'Hostel'), ('2', 'Traveler')], default=1, max_length=255),
        ),
    ]
