# Generated by Django 3.0.6 on 2020-09-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_remove_customerprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_hostel',
        ),
    ]
