# Generated by Django 3.0.6 on 2020-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_auto_20200917_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
