# Generated by Django 3.0.6 on 2020-12-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_customerprofile_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Zip/Postal Code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Zip/Postal Code'),
        ),
        migrations.AddField(
            model_name='request',
            name='zip_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Zip/Postal Code'),
        ),
    ]
