# Generated by Django 3.0.6 on 2021-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_auto_20210217_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/pictures/791218_man_512x512.png', null=True, upload_to='pictures'),
        ),
    ]
