# Generated by Django 3.0.6 on 2021-03-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_profile_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
