# Generated by Django 3.0.6 on 2021-03-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_profile_stripe_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_refresh_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
