# Generated by Django 3.0.6 on 2021-03-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_profile_stripe_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
