# Generated by Django 3.0.6 on 2021-08-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_auto_20210801_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='pictures/791218_man_512x512.png', null=True, upload_to='pictures'),
        ),
    ]
