# Generated by Django 3.0.6 on 2021-08-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_auto_20210802_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_experation',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
