# Generated by Django 3.0.6 on 2021-08-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_auto_20210811_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_experation',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
