# Generated by Django 3.0.6 on 2021-08-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_auto_20210812_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_experation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_experation',
            field=models.DateTimeField(null=True),
        ),
    ]
