# Generated by Django 3.0.6 on 2021-08-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_auto_20210812_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_experation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_experation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
