# Generated by Django 3.0.6 on 2021-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_auto_20210812_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
