# Generated by Django 3.0.6 on 2021-08-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_auto_20210812_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_checked_in',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_history',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='made_on',
        ),
    ]
