# Generated by Django 3.0.6 on 2021-10-15 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_auto_20210812_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_experation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 17, 3, 1), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_experation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 16, 3, 1), editable=False, null=True),
        ),
    ]
