runtime: python37 # or python37 for Python 3.7
#entrypoint: gunicorn -b :$PORT getLost.wsgi:application
instance_class: F2

#env_variables:
#  BUCKET_NAME: "example-gcs-bucket"

handlers:
# Matches requests to /images/... to files in static/images/...
#- url: /images
#  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

